Repository validmind/documentation, pull requests merged in 2024-12, with the labels that each got.

#559 Fixing on the fly notebook execution filter
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
  .github/workflows/validate-docs-site.yaml
  site/notebooks/README.md
Labels: internal

#561 1 last attempt at the execution workflows
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
  site/notebooks/README.md
Labels: internal

#548 Update log-in-to-validmind.qmd
  site/guide/configuration/log-in-to-validmind.qmd
Labels: internal

#564 Filtering for changes on prod/staging
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
Labels: internal

#567 Live notebook execution workflows, take ... whatever
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
  site/notebooks/README.md
Labels: internal

#569 Execution workflows are driving Beck insane
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
  site/notebooks/README.md
Labels: internal

#572 Removing the workflow filters for staging & prod
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
Labels: internal

#581 Docs — Customize inventory & findings lists
  internal/templates/_single-source.qmd
  site/about/contributing/style-guide/conventions.qmd
  site/about/overview-model-risk-management.qmd
  site/developer/model-documentation/install-and-initialize-validmind-library.qmd
  site/developer/model-documentation/store-credentials-in-env-file.qmd
  site/developer/model-documentation/work-with-test-results.qmd
  site/faq/faq.qmd
  site/get-started/platform/explore-sample-model-documentation.qmd
  site/get-started/platform/register-your-first-model.qmd
  site/guide/model-documentation/_add-content-block.qmd
  site/guide/model-documentation/_review-model-documentation.qmd
  site/guide/model-documentation/assign-documentation-section-statuses.qmd
  site/guide/model-documentation/export-documentation.qmd
  site/guide/model-documentation/swap-documentation-templates.qmd
  site/guide/model-documentation/view-documentation-guidelines.qmd
  site/guide/model-documentation/work-with-content-blocks.qmd
  site/guide/model-inventory/_remove-layout-view.qmd
  site/guide/model-inventory/_save-layout-view.qmd
  site/guide/model-inventory/_view-model-activity-steps.qmd
  site/guide/model-inventory/archive-delete-models.qmd
  site/guide/model-inventory/configure-model-interdependencies.qmd
  site/guide/model-inventory/customize-model-inventory-layout.qmd
  site/guide/model-inventory/edit-model-inventory-fields.qmd
  site/guide/model-inventory/manage-model-inventory-fields.qmd
  site/guide/model-inventory/register-models-in-inventory.qmd
  site/guide/model-inventory/working-with-model-inventory.qmd
  site/guide/model-validation/_add-model-findings.qmd
  site/guide/model-validation/_assess-compliance-assess.qmd
  site/guide/model-validation/_assess-compliance-developer-evidence.qmd
  site/guide/model-validation/_assess-compliance-link-finding.qmd
  site/guide/model-validation/_track_issue_resolution.qmd
  site/guide/model-validation/add-manage-model-findings.qmd
  site/guide/model-validation/assess-compliance.qmd
  site/guide/model-validation/manage-finding-columns-demo.gif
  site/guide/model-validation/preparing-validation-reports.qmd
  site/guide/model-validation/view-filter-model-findings.qmd
  site/guide/model-workflows/_model-workflows-see.qmd
  site/guide/model-workflows/_model-workflows-transition.qmd
  site/guide/model-workflows/working-with-model-workflows.qmd
  site/guide/monitoring/enable-monitoring.qmd
  site/guide/monitoring/review-monitoring-results.qmd
  site/guide/monitoring/work-with-metrics-over-time.qmd
  site/releases/2023/2023-nov-09/highlights.qmd
  site/releases/2023/release-notes-2023-may-30.qmd
  site/releases/2024-aug-13/release-notes.qmd
  site/releases/2024-feb-14/highlights.qmd
  site/releases/2024-mar-27/highlights.qmd
  site/releases/2024-may-22/release-notes.qmd
  site/training/developer-fundamentals/developer-fundamentals.qmd
  site/training/validator-fundamentals/validator-fundamentals.qmd
Labels: internal

#583 Docs — Adding custom dashboards & widgets
  site/guide/configuration/customize-your-dashboard.qmd
Labels: internal

#582 Add support chatbot to docs site
  site/_quarto-development.yml
  site/_quarto-production.yml
  site/_quarto-staging.yml
  site/support/support.qmd
  site/training/_training-support.qmd
  site/zendesk-chat.html
Labels: infrastructure, internal

#588 Fix link to SR 11-7
  site/about/glossary/_models.qmd
Labels: bug, internal

#591 Forgot the guides in the dropdown
  site/_quarto.yml
Labels: internal

#593 Docs quick audit — ValidMind Library
  site/_quarto.yml
  site/about/overview-model-documentation.qmd
  site/developer/get-started-validmind-library.qmd
  site/developer/model-documentation/install-and-initialize-validmind-library.qmd
  site/developer/model-documentation/supported-models.qmd
  site/developer/model-testing/test-descriptions.qmd
  site/developer/model-testing/test-sandbox.qmd
  site/developer/model-testing/testing-overview.qmd
  site/developer/samples-jupyter-notebooks.qmd
  site/get-started/get-started.qmd
  site/releases/2024-jun-10/release-notes.qmd
Labels: internal

#594 Add Docker image for our docs site
  Dockerfile
  README.md
  site/Makefile
Labels: infrastructure, internal

#599 Cleaned up Developer Fundamentals & other training
  site/training/administrator-fundamentals/administrator-fundamentals-register.qmd
  site/training/administrator-fundamentals/administrator-fundamentals.qmd
  site/training/developer-fundamentals/developer-fundamentals-register.qmd
  site/training/developer-fundamentals/developer-fundamentals.qmd
  site/training/validator-fundamentals/validator-fundamentals-register.qmd
  site/training/validator-fundamentals/validator-fundamentals.qmd
Labels: internal

#600 Delete test-results directory
  test-results/.last-run.json
Labels: infrastructure, internal

#596 Release notes — December 24, 2024
  site/_quarto.yml
  site/about/overview-llm-features.qmd
  site/guide/model-documentation/customize-documentation-templates.qmd
  site/guide/model-documentation/work-with-content-blocks.qmd
  site/guide/model-inventory/manage-model-inventory-fields.qmd
  site/guide/model-inventory/working-with-model-inventory.qmd
  site/guide/reporting/_reports-metrics.qmd
  site/guide/reporting/manage-custom-reports.qmd
  site/index.qmd
  site/python-docs.zip
  site/releases/2023/2023-aug-15/highlights.qmd
  site/releases/2023/2023-dec-13/highlights.qmd
  site/releases/2023/2023-nov-09/highlights.qmd
  site/releases/2023/2023-oct-25/highlights.qmd
  site/releases/2023/2023-sep-27/highlights.qmd
  site/releases/2023/release-notes-2023-jul-24.qmd
  site/releases/2023/release-notes-2023-jun-22.qmd
  site/releases/2023/release-notes-2023-may-30.qmd
  site/releases/2024-aug-13/release-notes.qmd
  site/releases/2024-dec-06/release-notes.qmd
  site/releases/2024-dec-24/custom-dashboard.png
  site/releases/2024-dec-24/delete-linked-finding.png
  site/releases/2024-dec-24/developer-only-field.png
  site/releases/2024-dec-24/faq.png
  site/releases/2024-dec-24/help-center.png
  site/releases/2024-dec-24/log-in.png
  site/releases/2024-dec-24/new-developer-portal.png
  site/releases/2024-dec-24/new-homepage-search.png
  site/releases/2024-dec-24/new-training-nav.png
  site/releases/2024-dec-24/old-homepage-search.png
  site/releases/2024-dec-24/old-training-nav.png
  site/releases/2024-dec-24/release-notes.qmd
  site/releases/2024-dec-24/revision-history.png
  site/releases/2024-feb-14/highlights.qmd
  site/releases/2024-jan-18/highlights.qmd
  site/releases/2024-jan-26/highlights.qmd
  site/releases/2024-jul-22/release-notes.qmd
  site/releases/2024-jun-10/release-notes.qmd
  site/releases/2024-mar-27/highlights.qmd
  site/releases/2024-may-22/release-notes.qmd
  site/releases/2024-oct-22/release-notes.qmd
  site/releases/2024-releases.qmd
  site/releases/2024-sep-09/release-notes.qmd
  site/support/support.qmd
Labels: internal

#606 Resolving publication conflicts for PR#605
  site/about/overview-llm-features.qmd
  site/releases/2023/2023-aug-15/highlights.qmd
Labels: internal

#607 Edited release script & notebook
  .gitignore
  release-scripts/__pycache__/generate_release_objects.cpython-311.pyc
  release-scripts/generate-release-notes.ipynb
  release-scripts/generate_release_objects.py
  site/Makefile
  site/index.qmd
Labels: internal

#613 Missing footnote from FAQ
  site/faq/faq-workflows.qmd
Labels: internal
