Repository validmind/documentation, pull requests merged in 2024-11, with the labels that each got.

#505 Documentation for filtering test result metadata
  site/developer/model-documentation/test-run-details.gif
  site/developer/model-documentation/work-with-test-results.qmd
  site/guide/model-documentation/_collaborate-with-others-comments.qmd
  site/guide/model-documentation/collaborate-with-others.qmd
  site/guide/model-validation/view-filter-model-findings.qmd
  site/index.qmd
  site/python-docs.zip
  site/styles.css
Labels: internal

#510 Document LLM features
  site/_extensions/nrichers/preview/preview.css
  site/_extensions/nrichers/preview/preview.lua
  site/_quarto.yml
  site/about/deployment/multi-tenant-cloud.qmd
  site/about/deployment/virtual-private-validmind.qmd
  site/about/overview-llm-features-check-document-in-progress.gif
  site/about/overview-llm-features-check-document-output.png
  site/about/overview-llm-features-check-document.png
  site/about/overview-llm-features.qmd
  site/styles.css
Labels: documentation

#517 Quick gallery css
  internal/testing/lightbox.qmd
  site/_quarto.yml
  site/styles.css
Labels: internal

#520 Quick adjustment to hero BG img for training
  site/training/assets/training.css
Labels: internal

#524 New sidebar & ToC theme
  site/about/contributing/style-guide/conventions.qmd
  site/index.qmd
  site/styles.css
  site/training/administrator-fundamentals/administrator-fundamentals-register.qmd
  site/training/assets/training-nav.css
  site/training/assets/training.css
  site/training/developer-fundamentals/developer-fundamentals-register.qmd
  site/training/training-templates/course-registration.qmd
  site/training/validator-fundamentals/validator-fundamentals-register.qmd
Labels: internal

#529 Updated `validmind-library` repo URL for `documentation` side
  README.md
  site/Makefile
  site/about/contributing/validmind-community.qmd
  site/about/glossary/_validmind.qmd
  site/developer/get-started-validmind-library.qmd
  site/developer/model-documentation/install-and-initialize-validmind-library.qmd
  site/developer/samples-jupyter-notebooks.qmd
  site/developer/validmind-ai-risk-platform.png
  site/get-started/developer/try-in-your-own-environment.qmd
  site/index.qmd
  site/releases/2023/2023-nov-09/highlights.qmd
  site/releases/2023/2023-oct-25/highlights.qmd
  site/releases/2024-aug-13/release-notes.qmd
  site/releases/2024-feb-14/highlights.qmd
  site/releases/2024-jan-26/highlights.qmd
  site/releases/2024-jul-22/release-notes.qmd
  site/releases/2024-mar-27/highlights.qmd
  site/releases/2024-may-22/release-notes.qmd
  site/releases/2024-oct-22/release-notes.qmd
Labels: internal

#531 Quick CSS cleanup
  site/about/contributing/style-guide/conventions.qmd
  site/releases/2024-oct-22/release-notes.qmd
  site/styles.css
  site/training/training.qmd
Labels: internal

#535 Fixing weird columns on release pages on `prod`
  README.md
  site/Makefile
  site/about/contributing/style-guide/conventions.qmd
  site/about/contributing/validmind-community.qmd
  site/about/glossary/_validmind.qmd
  site/developer/get-started-validmind-library.qmd
  site/developer/model-documentation/install-and-initialize-validmind-library.qmd
  site/developer/samples-jupyter-notebooks.qmd
  site/developer/validmind-ai-risk-platform.png
  site/get-started/developer/try-in-your-own-environment.qmd
  site/index.qmd
  site/releases/2023/2023-nov-09/highlights.qmd
  site/releases/2023/2023-oct-25/highlights.qmd
  site/releases/2024-aug-13/release-notes.qmd
  site/releases/2024-feb-14/highlights.qmd
  site/releases/2024-jan-18/highlights.qmd
  site/releases/2024-jan-26/highlights.qmd
  site/releases/2024-jul-22/release-notes.qmd
  site/releases/2024-mar-27/highlights.qmd
  site/releases/2024-may-22/release-notes.qmd
  site/releases/2024-oct-22/release-notes.qmd
  site/styles.css
  site/training/training.qmd
Labels: internal

#534 Pushing to prod PR#525 onward
  README.md
  site/Makefile
  site/about/contributing/style-guide/conventions.qmd
  site/about/contributing/validmind-community.qmd
  site/about/glossary/_validmind.qmd
  site/developer/get-started-validmind-library.qmd
  site/developer/model-documentation/install-and-initialize-validmind-library.qmd
  site/developer/samples-jupyter-notebooks.qmd
  site/developer/validmind-ai-risk-platform.png
  site/get-started/developer/try-in-your-own-environment.qmd
  site/index.qmd
  site/releases/2023/2023-nov-09/highlights.qmd
  site/releases/2023/2023-oct-25/highlights.qmd
  site/releases/2024-aug-13/release-notes.qmd
  site/releases/2024-feb-14/highlights.qmd
  site/releases/2024-jan-26/highlights.qmd
  site/releases/2024-jul-22/release-notes.qmd
  site/releases/2024-mar-27/highlights.qmd
  site/releases/2024-may-22/release-notes.qmd
  site/releases/2024-oct-22/release-notes.qmd
  site/styles.css
  site/training/training.qmd
Labels: internal

#540 Added quick instructions on submitting feedback within the platform
  site/support/support.qmd
  site/support/talk-to-us.png
  site/training/_training-support.qmd
Labels: internal

#539 Replace Output Template Notebook from Highlighted Code Samples
  site/developer/get-started-validmind-library.qmd
Labels: internal, deprecation

#538 Making changes for Mehdi :)
  site/guide/model-inventory/archive-delete-models.qmd
Labels: internal

#544 Add login button to docs site
  site/_quarto.yml
  site/guide/configuration/log-in-to-validmind.qmd
  site/styles.css
  site/training/assets/training.css
Labels: documentation

#554 Quick workflow filter tweak
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
  .github/workflows/validate-docs-site.yaml
  site/_quarto.yml
  site/notebooks/README.md
Labels: internal

#555 Updated "Assess compliance" for new evidence structure
  site/get-started/platform/explore-sample-model-documentation.qmd
  site/guide/model-validation/_assess-compliance-assess.qmd
  site/guide/model-validation/_assess-compliance-developer-evidence.qmd
  site/guide/model-validation/_assess-compliance-link-evidence.qmd
  site/guide/model-validation/_assess-compliance-link-finding.qmd
  site/guide/model-validation/add-manage-model-findings.qmd
  site/guide/model-validation/assess-compliance.qmd
  site/guide/model-validation/link-developer-evidence.png
  site/guide/model-validation/link-finding.png
  site/guide/model-validation/link-validator-evidence.png
  site/styles.css
  site/training/assets/slides.scss
  site/training/validator-fundamentals/validator-fundamentals.qmd
Labels: internal
