Repository validmind/documentation, pull requests merged in 2024-09, with the labels that each got.

#300 Add initial staging branch workflow
  .github/workflows/merge-main-into-staging.yaml
Labels: infrastructure, internal

#329 Release notes for Sept 9 2024
  site/_quarto.yml
  site/guide/model-workflows/working-with-model-workflows.qmd
  site/releases/2024-may-22/release-notes.qmd
  site/releases/2024-releases.qmd
  site/releases/2024-sep-09/release-notes.qmd
  site/releases/2024-sep-09/reset-model-workflow.png
  site/releases/2024-sep-09/settings-validation-guidelines.png
Labels: internal

#330 Only running the PR previews bot when a PR is ready for review
  .github/workflows/ai_explain.yaml
Labels: infrastructure, internal

#344 Delete old .github/workflows/render-site.yaml workflow
  .github/workflows/render-site.yaml
Labels: infrastructure, internal

#334 Investigate listing page issue
  site/developer/model-testing/test-descriptions.qmd
Labels: infrastructure, internal

#339 Fix Heap embeds for docs sites — `main` branch
  site/_quarto.yml
  site/heap-development.html
Labels: infrastructure, internal

#340 Fix Heap embeds for docs sites — `staging` branch
  site/_quarto.yml
Labels: infrastructure, internal

#351 Doc: Archive and delete inventory models
  site/_quarto.yml
  site/guide/model-inventory/archive-delete-models.qmd
  site/guide/model-inventory/managing-model-inventory.qmd
Labels: enhancement

#352 Revamped model findings docs for attachments
  site/_quarto.yml
  site/guide/guides.qmd
  site/guide/model-documentation/_model-documentation-overview.qmd
  site/guide/model-documentation/_view-documentation-activity-overview.qmd
  site/guide/model-documentation/collaborate-with-others.qmd
  site/guide/model-documentation/view-documentation-activity.qmd
  site/guide/model-documentation/view-documentation-guidelines.qmd
  site/guide/model-validation/_add-model-findings.qmd
  site/guide/model-validation/_assess-compliance-assess.qmd
  site/guide/model-validation/_assess-compliance-link-finding.qmd
  site/guide/model-validation/add-section-finding.gif
  site/guide/model-validation/add-update-model-findings.qmd
  site/guide/model-validation/all-model-findings.png
  site/guide/model-validation/assess-compliance.qmd
  site/guide/model-validation/delete-finding-attachment.gif
  site/guide/model-validation/manage-validation-guidelines.qmd
  site/guide/model-validation/model-specific-findings.png
  site/guide/model-validation/review-model-documentation.qmd
  site/guide/model-validation/view-filter-model-findings.qmd
  site/guide/model-validation/view-reports.qmd
  site/guide/model-validation/work-with-model-findings.qmd
  site/guide/model-validation/working-with-model-findings.qmd
  site/releases/2023/release-notes-2023-jul-24.qmd
  site/releases/2024-may-22/release-notes.qmd
  site/support/troubleshooting.qmd
  site/training/training-for-model-validators.qmd
Labels: internal

#358 Moved activity to model inventory & adjusted pages
  site/_quarto.yml
  site/developer/model-documentation/work-with-test-results.qmd
  site/guide/guides.qmd
  site/guide/model-documentation/_model-documentation-overview.qmd
  site/guide/model-documentation/assign-documentation-section-statuses.qmd
  site/guide/model-documentation/collaborate-with-others.qmd
  site/guide/model-documentation/submit-for-approval.qmd
  site/guide/model-documentation/work-with-content-blocks.qmd
  site/guide/model-documentation/working-with-model-documentation.qmd
  site/guide/model-inventory/_view-model-activity-overview.qmd
  site/guide/model-inventory/_view-model-activity-steps.qmd
  site/guide/model-inventory/view-model-activity.qmd
  site/guide/model-validation/add-manage-model-findings.qmd
  site/guide/model-validation/assess-compliance.qmd
  site/guide/model-validation/preparing-validation-reports.qmd
  site/guide/model-validation/review-model-documentation.qmd
  site/guide/model-validation/working-with-model-findings.qmd
  site/training/training-for-model-developers.qmd
Labels: internal

#227 Training updates related to creating videos
  site/_quarto.yml
  site/about/glossary/validation_reports/_review.qmd
  site/releases/2024-may-22/release-notes.qmd
  site/training/custom.scss
  site/training/laurels_pink.png
  site/training/training-for-administrators.qmd
  site/training/training-for-model-developers.qmd
  site/training/training-for-model-risk-governance.qmd
  site/training/training-for-model-validators.qmd
  site/training/training.qmd
Labels: internal

#363 Clarified style guidelines for links & training
  site/about/contributing/style-guide/conventions.qmd
  site/about/contributing/style-guide/training-overlay.png
  site/about/contributing/style-guide/training_inline-links.png
  site/about/contributing/style-guide/user-guide_footenotes.png
Labels: internal

#366 Adding new ValidMind colors & logo
  site/about/ValidMind-logo-color.svg
  site/index.qmd
  site/styles.css
Labels: internal

#368 Update workflows to trigger on workflow_run
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
Labels: infrastructure, internal

#369 Update README.md
  README.md
Labels: internal

#372 Use Quarto profiles for rendering the site on GitHub and locally
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
  .github/workflows/validate-docs-site.yaml
  site/Makefile
  site/_quarto-development.yml
  site/_quarto-production.yml
  site/_quarto-staging.yml
  site/environments/heap-development.html
  site/environments/heap-production.html
  site/environments/heap-staging.html
Labels: infrastructure, internal

#377 Docs site audit accuracy tone review — Guides p1
  site/about/contributing/style-guide/voice-and-tone.qmd
  site/about/glossary/validation_reports/_review.qmd
  site/guide/configuration/_manage-groups-add.qmd
  site/guide/configuration/_manage-roles.qmd
  site/guide/configuration/_manage-users-invite.qmd
  site/guide/configuration/_manage-users-monitor.qmd
  site/guide/configuration/_set-up-your-organization-business-units.qmd
  site/guide/configuration/_set-up-your-organization-risk-areas.qmd
  site/guide/configuration/_set-up-your-organization-use-cases.qmd
  site/guide/configuration/configure-aws-privatelink.qmd
  site/guide/configuration/configure-google-private-service-connect.qmd
  site/guide/configuration/customize-your-dashboard.qmd
  site/guide/configuration/log-in-to-validmind.qmd
  site/guide/configuration/manage-groups.qmd
  site/guide/configuration/manage-users.qmd
  site/guide/configuration/manage-your-profile.qmd
  site/guide/configuration/managing-users.qmd
  site/guide/guides.qmd
  site/guide/model-documentation/_collaborate-with-others-activity.qmd
  site/guide/model-documentation/_collaborate-with-others-comments.qmd
  site/guide/model-documentation/_customize-documentation-templates-simplified.qmd
  site/guide/model-documentation/assign-documentation-section-statuses.qmd
  site/guide/model-documentation/collaborate-with-others.qmd
  site/guide/model-documentation/customize-documentation-templates.qmd
  site/guide/model-documentation/export-documentation.qmd
  site/guide/model-documentation/submit-for-approval.qmd
  site/guide/model-documentation/swap-documentation-templates.qmd
  site/guide/model-documentation/view-documentation-templates.qmd
  site/guide/model-inventory/archive-delete-models.qmd
  site/guide/model-inventory/configure-model-interdependencies.qmd
  site/guide/model-inventory/customize-model-inventory-layout.qmd
  site/guide/model-inventory/edit-model-inventory-fields.qmd
  site/guide/model-inventory/manage-model-inventory-fields.qmd
  site/guide/model-inventory/register-models-in-inventory.qmd
  site/guide/model-inventory/view-model-activity.qmd
  site/guide/model-inventory/working-with-model-inventory.qmd
  site/guide/model-validation/_assess-compliance-assess.qmd
  site/guide/model-validation/_assess-compliance-link-evidence.qmd
  site/guide/model-validation/_assess-compliance-link-finding.qmd
  site/guide/model-validation/add-manage-model-findings.qmd
  site/guide/model-validation/assess-compliance-summary.png
  site/guide/model-validation/assess-compliance.qmd
  site/guide/model-validation/manage-validation-guidelines.qmd
  site/guide/model-validation/preparing-validation-reports.qmd
  site/guide/model-validation/review-model-documentation.qmd
  site/guide/model-validation/view-filter-model-findings.qmd
  site/guide/model-workflows/_model-workflows-transition.qmd
  site/guide/model-workflows/customize-model-lifecycle-statuses.qmd
  site/guide/model-workflows/set-up-model-workflows.qmd
  site/guide/model-workflows/working-with-model-workflows.qmd
  site/guide/monitoring/enable-monitoring.qmd
  site/guide/monitoring/review-monitoring-results.qmd
  site/training/training-for-model-developers.qmd
  site/training/training-for-model-validators.qmd
Labels: internal

#392 Update README.md
  README.md
Labels: internal

#409 Revamped View reports
  site/guide/model-validation/reports-findings.png
  site/guide/model-validation/reports-models.png
  site/guide/model-validation/view-filter-model-findings.qmd
  site/guide/model-validation/view-reports.qmd
Labels: internal

#390 Updated Work with content blocks
  site/about/glossary/_validmind-features.qmd
  site/guide/model-documentation/_add-content-block.qmd
  site/guide/model-documentation/add-content-block.gif
  site/guide/model-documentation/content-editing-toolbar.png
  site/guide/model-documentation/content_blocks/_metric-over-time-block.qmd
  site/guide/model-documentation/content_blocks/_simple-text-block.qmd
  site/guide/model-documentation/content_blocks/_test-driven-block.qmd
  site/guide/model-documentation/swap-documentation-templates.qmd
  site/guide/model-documentation/view-documentation-templates.qmd
  site/guide/model-documentation/work-with-content-blocks.qmd
  site/guide/model-inventory/_view-model-activity-overview.qmd
  site/guide/model-inventory/view-model-activity.qmd
Labels: internal

#412 Make training slides more photogenic
  site/training/custom.scss
  site/training/home-hero.svg
  site/training/training-for-administrators.qmd
  site/training/training-for-model-developers.qmd
  site/training/training-for-model-risk-governance.qmd
  site/training/training-for-model-validators.qmd
  site/training/training.qmd
Labels: documentation

#410 Documented user registration process
  internal/templates/about-validmind.md
  site/_quarto.yml
  site/_variables.yml
  site/get-started/developer/try-in-your-own-environment.qmd
  site/get-started/developer/try-with-colab.qmd
  site/get-started/developer/try-with-jupyterhub.qmd
  site/get-started/get-started.qmd
  site/get-started/platform/explore-sample-model-documentation.qmd
  site/get-started/platform/generate-documentation-for-your-model.qmd
  site/get-started/platform/register-your-first-model.qmd
  site/get-started/quickstart.qmd
  site/guide/configuration/_validmind-public-internet.qmd
  site/guide/configuration/accessing-validmind.qmd
  site/guide/configuration/email-verified.png
  site/guide/configuration/log-in-to-validmind.qmd
  site/guide/configuration/main-dashboard.png
  site/guide/configuration/organization-accept-invitation.png
  site/guide/configuration/organization-invitation-email.png
  site/guide/configuration/register-with-validmind.qmd
  site/guide/configuration/sample-models.png
  site/guide/configuration/signup-complete-profile.png
  site/guide/configuration/signup-welcome-screen.png
  site/guide/configuration/verify-email.png
  site/guide/guides.qmd
Labels: internal

#424 Fix merge conflicts for Sep 20
  site/Makefile
  site/guide/model-documentation/_customize-documentation-templates-simplified.qmd
  site/guide/model-documentation/_view-documentation-activity-overview.qmd
  site/guide/model-documentation/_view-documentation-activity-steps.qmd
  site/guide/model-documentation/view-documentation-activity.qmd
  site/guide/model-validation/_work-with-model-findings-add-findings.qmd
  site/guide/model-validation/add-update-model-findings.qmd
  site/guide/model-validation/work-with-model-findings.qmd
  site/heap-development.html
  site/heap-production.html
  site/notebooks/README.md
  site/tests/data_validation/ANOVAOneWayTable.md
  site/tests/data_validation/BivariateFeaturesBarPlots.md
  site/tests/data_validation/BivariateHistograms.md
  site/tests/data_validation/HeatmapFeatureCorrelations.md
  site/tests/data_validation/MissingValuesRisk.md
  site/training/training-overview.qmd
Labels: internal

#428 Fix staging deploy in Makefile
  site/Makefile
Labels: internal

#373 Simplify merge strategy for staging
  .github/workflows/merge-main-into-staging.yaml
Labels: infrastructure, internal

#431 Testing simplified merge strategy
  README.md
Labels: internal

#432 Fix branch in merge-main-into-staging.yaml
  .github/workflows/merge-main-into-staging.yaml
Labels: infrastructure, internal

#434 Staging
  .github/workflows/merge-main-into-staging.yaml
  README.md
  site/Makefile
Labels: internal

#423 Added currency field type to inventory field docs
  site/guide/model-inventory/manage-model-inventory-fields.qmd
  site/guide/model-inventory/number-currency.png
  site/guide/model-inventory/number-simple.png
Labels: internal

#419 Preview of Generate with AI docs sections
  site/_quarto.yml
  site/guide/model-documentation/generate-with-ai.gif
  site/guide/model-documentation/work-with-content-blocks.qmd
  site/releases/2024-releases.qmd
  site/releases/2024-sep-25/ai-content-builder.png
  site/releases/2024-sep-25/generate-ai-prompt.png
  site/releases/2024-sep-25/generate-with-ai.png
  site/releases/2024-sep-25/release-notes.qmd
Labels: internal

#442 Added attachment field type
  site/guide/model-documentation/work-with-content-blocks.qmd
  site/guide/model-inventory/edit-model-inventory-fields.qmd
  site/guide/model-inventory/manage-model-inventory-fields.qmd
  site/guide/model-validation/add-manage-model-findings.qmd
Labels: internal

#444 Added new aliases to `training.qmd`
  site/training/training.qmd
Labels: internal

#449 Docs: Work with metrics over time
  site/_quarto.yml
  site/developer/model-documentation/work-with-test-results.qmd
  site/guide/model-documentation/_add-content-block.qmd
  site/guide/model-documentation/work-with-content-blocks.qmd
  site/guide/monitoring/enable-monitoring.qmd
  site/guide/monitoring/metric-over-time-data.png
  site/guide/monitoring/metrics-over-time-menu.png
  site/guide/monitoring/ongoing-monitoring.qmd
  site/guide/monitoring/review-monitoring-results.qmd
  site/guide/monitoring/work-with-metrics-over-time.qmd
Labels: internal

#443 Calculation field instructions & example
  site/guide/model-inventory/calculation-field.png
  site/guide/model-inventory/manage-model-inventory-fields.qmd
Labels: internal

#446 Embed Validating Models 101 playlist into Guides section
  site/guide/guides.qmd
Labels: documentation

#450 Embed "How do I ... add tests?" video in developer docs
  site/developer/model-testing/testing-overview.qmd
Labels: documentation
