Repository validmind/documentation, pull requests merged in 2024-05, with the labels that each got.

#177 Nrichers/sc 2887/release notes script updates
  site/Makefile
  site/_quarto.yml
  site/generate_release_notes.py
  site/scripts/generate_release_notes.py
  templates/release_highlights_template.qmd
Labels: infrastructure, internal

#184 Remove closed beta info
  site-unused/closed-beta-banner.png
  site-unused/get-started-closed-beta.qmd
  site-unused/join-closed-beta.qmd
  site/_quarto.yml
  site/_site/about/data-privacy-policy.html
  site/_site/about/glossary/glossary.html
  site/_site/about/license-agreement.html
  site/_site/about/overview-model-documentation.html
  site/_site/about/overview-model-risk-management.html
  site/_site/about/overview.html
  site/_site/about/style-guide.html
  site/_site/about/validmind-community.html
  site/_site/guide/closed-beta-banner.png
  site/_site/guide/developer-getting-started-video.html
  site/_site/guide/get-started-closed-beta.html
  site/_site/guide/get-started-developer-framework.html
  site/_site/guide/get-started.html
  site/_site/guide/guides.html
  site/_site/guide/join-closed-beta.html
  site/_site/guide/preparing-validation-reports.html
  site/_site/guide/release-notes-2023-jul-24.html
  site/_site/guide/release-notes-2023-jun-22.html
  site/_site/guide/release-notes-2023-may-30.html
  site/_site/guide/testing-overview.html
  site/_site/guide/working-with-model-documentation.html
  site/_site/releases/2023-aug-15/highlights.html
  site/_site/releases/2023-dec-13/highlights.html
  site/_site/releases/2023-nov-09/highlights.html
  site/_site/releases/2023-oct-25/highlights.html
  site/_site/releases/2023-sep-27/highlights.html
  site/_site/releases/2024-feb-14/highlights.html
  site/_site/releases/2024-jan-18/highlights.html
  site/_site/releases/2024-jan-26/highlights.html
  site/_site/releases/2024-mar-27/highlights.html
  site/_site/search.json
  site/guide/closed-beta-banner.png
  site/guide/developer-getting-started-video.qmd
Labels: internal

#186 Fix .gitgnore files and add .env example file
  .gitignore
  site/.env.example
  site/.gitignore
Labels: infrastructure, internal

#187 Add QuickStart video to the docs site
  site/_site/about/glossary/glossary.html
  site/_site/about/style-guide.html
  site/_site/guide/developer-getting-started-video.html
  site/_site/guide/get-started-developer-framework.html
  site/_site/guide/get-started.html
  site/_site/guide/guides.html
  site/_site/guide/preparing-validation-reports.html
  site/_site/guide/quickstart-explore-sample-model-documentation.html
  site/_site/guide/quickstart-generate-documentation-for-your-model.html
  site/_site/guide/quickstart-register-your-first-model.html
  site/_site/guide/quickstart-try-developer-framework-in-your-own-developer-environment.html
  site/_site/guide/quickstart-try-developer-framework-with-colab.html
  site/_site/guide/quickstart-try-developer-framework-with-jupyterhub.html
  site/_site/guide/testing-overview.html
  site/_site/guide/working-with-model-documentation.html
  site/_site/search.json
  site/guide/get-started-developer-framework.qmd
  site/guide/quickstart-try-developer-framework-with-jupyterhub.qmd
Labels: documentation

#189 Move .env and .env.example into root of repo
  .env.example
  .gitignore
  site/scripts/generate_release_notes.py
Labels: infrastructure, internal

#197 New "Assign documentation section statuses" page in Guides
  site/_site/guide/guides.html
  site/_site/guide/testing-overview.html
  site/_site/guide/working-with-model-documentation.html
  site/_site/listings.json
  site/_site/search.json
  site/guide/working-with-model-documentation.qmd
Labels: internal

#205 Adding model vendor support
  site/_site/about/glossary/glossary.html
  site/_site/guide/guides.html
  site/_site/guide/preparing-validation-reports.html
  site/_site/guide/register-models-in-model-inventory.html
  site/_site/guide/supported-models.html
  site/_site/guide/working-with-documentation-templates.html
  site/_site/guide/working-with-model-documentation.html
  site/_site/search.json
  site/about/glossary/_models.qmd
  site/guide/register-models-in-model-inventory.qmd
  site/guide/supported-models.qmd
Labels: internal
