Repository validmind/documentation, pull requests merged in 2024-10, with the labels that each got.

#460 Add link to GitHub for code samples
  site/developer/samples-jupyter-notebooks.qmd
Labels: documentation

#468 Resolved janky footer styling
  site/styles.css
Labels: internal

#459 Deployment architecture docs
  site/_quarto.yml
  site/_variables.yml
  site/about/deployment/deployment-options.qmd
  site/about/deployment/multi-tenant-cloud.png
  site/about/deployment/multi-tenant-cloud.qmd
  site/about/deployment/validmind-architecture-overview.png
  site/about/deployment/virtual-private-validmind.png
  site/about/deployment/virtual-private-validmind.qmd
  site/about/fine-print/data-privacy-policy.qmd
  site/about/overview-model-documentation.qmd
  site/faq/faq-privacy.qmd
  site/guide/configuration/azure-private-link.png
  site/guide/configuration/configure-aws-privatelink.qmd
  site/guide/configuration/configure-azure-private-link.qmd
Labels: documentation

#469 Docs audit p2 — Get Started
  site/get-started/developer/try-in-your-own-environment.qmd
  site/get-started/developer/try-with-colab.qmd
  site/get-started/developer/try-with-jupyterhub.qmd
  site/get-started/get-started.qmd
  site/get-started/platform/explore-sample-model-documentation.qmd
  site/get-started/platform/generate-documentation-for-your-model.qmd
  site/get-started/platform/jupyterhub-secrets.png
  site/get-started/platform/model-registration.png
  site/get-started/platform/next-steps.qmd
  site/get-started/platform/platform-first-model.png
  site/get-started/platform/platform-getting-started.png
  site/get-started/platform/register-your-first-model.qmd
  site/get-started/quickstart.qmd
Labels: internal

#464 ValidExplain — Docs Site Chatbot MVP
  site/assets/img/events-people.png
  site/assets/img/standard-hero-dots-2-1024x620.png
  site/index.qmd
  site/scripts/validsearch.js
  site/styles.css
Labels: DO NOT MERGE, infrastructure, internal

#478 Docs audit p4 — About
  site/about/overview-model-documentation.qmd
  site/about/overview-model-risk-management.qmd
  site/about/overview.qmd
  site/get-started/get-started.qmd
  site/guide/configuration/manage-your-profile.qmd
  site/guide/model-inventory/_view-model-activity-overview.qmd
  site/guide/model-inventory/configure-model-interdependencies.qmd
  site/releases/2023/2023-aug-15/highlights.qmd
  site/releases/2023/2023-dec-13/highlights.qmd
  site/releases/2023/2023-nov-09/highlights.qmd
  site/releases/2023/2023-oct-25/highlights.qmd
  site/releases/2023/2023-sep-27/highlights.qmd
  site/releases/2023/release-notes-2023-jul-24.qmd
  site/releases/2023/release-notes-2023-jun-22.qmd
  site/releases/2023/release-notes-2023-may-30.qmd
  site/releases/2024-aug-13/release-notes.qmd
  site/releases/2024-feb-14/highlights.qmd
  site/releases/2024-jan-18/highlights.qmd
  site/releases/2024-jan-26/highlights.qmd
  site/releases/2024-jul-22/release-notes.qmd
  site/releases/2024-jun-10/release-notes.qmd
  site/releases/2024-mar-27/highlights.qmd
  site/releases/2024-may-22/release-notes.qmd
  site/releases/2024-sep-09/release-notes.qmd
  site/releases/2024-sep-25/release-notes.qmd
  site/releases/_how-to-upgrade.qmd
  site/styles.css
  site/support/support.qmd
  site/training/training-for-model-developers.qmd
  site/training/training.qmd
Labels: internal

#484 Documentation for Workflows - Condition Branches
  site/guide/model-inventory/manage-model-inventory-fields.qmd
  site/guide/model-workflows/configure-condition-branch.png
  site/guide/model-workflows/example-condition-branch.png
  site/guide/model-workflows/legal-team-approval.png
  site/guide/model-workflows/set-up-model-workflows.qmd
Labels: internal

#490 Instructions for upgrading ValidMind
  site/_variables.yml
  site/developer/model-documentation/install-and-initialize-client-library.qmd
  site/releases/_how-to-upgrade.qmd
  site/support/support.qmd
  site/support/troubleshooting.qmd
Labels: internal

#488 Rework training section & update validator training
  internal/templates/course.qmd
  site/_extensions/nrichers/preview/_extension.yaml
  site/_extensions/nrichers/preview/preview.css
  site/_extensions/nrichers/preview/preview.lua
  site/_quarto.yml
  site/about/contributing/style-guide/conventions.qmd
  site/guide/model-documentation/_add-content-block.qmd
  site/guide/model-documentation/_review-model-documentation.qmd
  site/guide/model-documentation/assign-documentation-section-statuses.qmd
  site/guide/model-documentation/export-documentation.qmd
  site/guide/model-documentation/swap-documentation-templates.qmd
  site/guide/model-documentation/view-documentation-guidelines.qmd
  site/guide/model-documentation/work-with-content-blocks.qmd
  site/guide/model-inventory/_view-model-activity-steps.qmd
  site/guide/model-inventory/archive-delete-models.qmd
  site/guide/model-inventory/configure-model-interdependencies.qmd
  site/guide/model-inventory/edit-model-inventory-fields.qmd
  site/guide/model-validation/_add-model-findings.qmd
  site/guide/model-validation/_assess-compliance-assess.qmd
  site/guide/model-validation/_assess-compliance-link-evidence.qmd
  site/guide/model-validation/_assess-compliance-link-finding.qmd
  site/guide/model-validation/_track_issue_resolution.qmd
  site/guide/model-validation/add-manage-model-findings.qmd
  site/guide/model-validation/preparing-validation-reports.qmd
  site/guide/model-validation/sample-model-findings.png
  site/guide/model-validation/view-filter-model-findings.qmd
  site/guide/model-workflows/_model-workflows-see.qmd
  site/guide/model-workflows/_model-workflows-transition.qmd
  site/guide/model-workflows/working-with-model-workflows.qmd
  site/guide/monitoring/enable-monitoring.qmd
  site/guide/monitoring/review-monitoring-results.qmd
  site/guide/monitoring/work-with-metrics-over-time.qmd
  site/index.qmd
  site/styles.css
  site/training/_revealjs-navigation.qmd
  site/training/_training-register.qmd
  site/training/_training-support.qmd
  site/training/administrator-fundamentals-register.qmd
  site/training/administrator-fundamentals.png
  site/training/administrator-fundamentals.qmd
  site/training/developer-fundamentals-register.qmd
  site/training/developer-fundamentals.png
  site/training/developer-fundamentals.qmd
  site/training/risk-governance-fundamentals.qmd
  site/training/training.qmd
  site/training/validator-fundamentals-register.qmd
  site/training/validator-fundamentals.png
  site/training/validator-fundamentals.qmd
Labels: documentation

#497 Adjusting training styles
  site/_extensions/nrichers/preview/preview.css
  site/about/contributing/style-guide/conventions.qmd
  site/index.qmd
  site/styles.css
  site/training/administrator-fundamentals-register.qmd
  site/training/training.qmd
Labels: internal

#495 Documented ability to add attachment notes
  site/guide/model-inventory/_manage-supporting-documentation-add.qmd
  site/guide/model-inventory/_manage-supporting-documentation-remove.qmd
  site/guide/model-inventory/add-attachment-note.gif
  site/guide/model-inventory/delete-attachments.gif
  site/guide/model-inventory/edit-model-inventory-fields.qmd
  site/guide/model-validation/add-manage-model-findings.qmd
  site/guide/model-validation/delete-finding-attachment.gif
Labels: internal
