Repository validmind/documentation, pull requests merged in 2025-09, with the labels that each got.

#926 docs: Workflow tasks in updates
  site/guide/_sidebar.yaml
  site/guide/configuration/manage-platform-notifications.qmd
  site/guide/model-workflows/manage-workflow-tasks.qmd
  site/guide/model-workflows/working-with-model-workflows.qmd
Labels: internal

#921 Removing validmind version variable
  site/_variables.yml
Labels: internal

#938 Update API reference to use prod server
  site/Makefile
  site/reference/validmind-rest-api-vm.qmd
  site/reference/vm-api.qmd
Labels: internal

#943 docs: Export inventory
  site/guide/_sidebar.yaml
  site/guide/guides.qmd
  site/guide/reporting/export-documents.qmd
  site/guide/reporting/export-findings.qmd
  site/guide/reporting/export-inventory.qmd
  site/guide/reporting/generating-exports.qmd
  site/releases/2025/2025-jan-31/release-notes.qmd
Labels: documentation

#954 docs: Workflow Wait step time delta configuration
  site/guide/model-workflows/_conditional-requirements.qmd
  site/guide/model-workflows/_workflow-step-types.qmd
  site/guide/model-workflows/configure_wait.png
Labels: internal

#962 Docs: Updated "Check documentation for compliance"
  site/guide/model-documentation/check-documentation-for-compliance.qmd
  site/guide/model-documentation/vdv-gap-identified.png
  site/guide/model-documentation/vdv-no-significant-gaps.png
  site/guide/model-documentation/vdv-partial-gap.png
Labels: internal

#935 Fix bug in Makefile for `INSTALLATION` option
  site/Makefile
Labels: infrastructure, internal

#968 Bug bash: nrichers/sc 12201/disable algolia search on api reference pages
  site/.gitignore
  site/reference/vm-api.qmd
Labels: bug, internal
