Repository validmind/documentation, pull requests merged in 2025-08, with the labels that each got.

#874 Add updated site/_variables.yml to prod to address merge conflict
  site/_variables.yml
Labels: internal

#866 Bump latest version to `25.08` and `v2.8.29`
  site/Makefile
  site/_quarto.yml
  site/index.qmd
  site/releases/documentation-releases.qmd
  site/releases/highlights.qmd
  site/releases/validmind-library-releases.qmd
  site/releases/validmind-platform-releases.qmd
  site/styles.css
  site/tests/model_validation/ragas/ResponseRelevancy.md
  site/tests/model_validation/sklearn/HyperParametersTuning.md
  site/validmind/_sidebar.yml
  site/validmind/validmind.qmd
  site/validmind/validmind/tests/prompt_validation/Bias.qmd
  site/validmind/validmind/tests/prompt_validation/Clarity.qmd
  site/validmind/validmind/tests/prompt_validation/Conciseness.qmd
  site/validmind/validmind/tests/prompt_validation/Delimitation.qmd
  site/validmind/validmind/tests/prompt_validation/NegativeInstruction.qmd
  site/validmind/validmind/tests/prompt_validation/Robustness.qmd
  site/validmind/validmind/tests/prompt_validation/Specificity.qmd
  site/validmind/validmind/tests/prompt_validation/ai_powered_test.qmd
  site/validmind/validmind/version.qmd
  site/validmind/validmind/vm_models.qmd
Labels: internal

#877 Check out makefile from staging
  site/Makefile
Labels: internal

#878 Check for WARNING in render log
  .github/workflows/validate-docs-site.yaml
Labels: bug, internal

#879 docs: Notes tracked on workflow transitions
  site/guide/model-workflows/_review-active-workflows.qmd
Labels: internal

#884 Workaround for Quarto render WARNING testing for notebook execution
  .github/workflows/validate-docs-site.yaml
  site/notebooks/EXECUTED/test.ipynb
Labels: internal

#886 Resolve merge conflicts for `prod` push #883
  .github/workflows/validate-docs-site.yaml
  site/guide/model-workflows/_review-active-workflows.qmd
  site/notebooks/EXECUTED/test.ipynb
Labels: internal

#889 Prod patch for PR#883
  site/notebooks/EXECUTED/test.ipynb
Labels: internal

#899 infra: Optimising deployment workflow runs
  .github/actions/free-disk-space/action.yml
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
  .github/workflows/validate-docs-site.yaml
Labels: internal

#903 Fix codeblock formatting issue and import as modular CSS
  README.md
  site/css/_bug-fixes.css
  site/css/_codeblocks.css
  site/guide/monitoring/set-thresholds-and-alerts.qmd
  site/styles.css
Labels: bug

#902 Nrichers/sc 11817/address docs login to directing to validmind
  site/_quarto-development.yml
  site/_quarto-production.yml
  site/_quarto-staging.yml
  site/_quarto.yml
  site/_variables.yml
  site/developer/developer.css
  site/guide/access/log-in-to-validmind.qmd
  site/styles.css
  site/training/assets/training.css
Labels: documentation, internal

#907 hotfix: validmind dependency fix for notebook execution
  .github/actions/demo-notebook/action.yml
  .github/actions/prod-notebook/action.yml
  .github/actions/staging-notebook/action.yml
  .github/workflows/validate-docs-site.yaml
Labels: internal

#908 Hotfix: add doc menu back to developer & training menus
  README.md
  internal/assets/custom-validmind_yaml_example.png
  site/developer/developer.css
  site/training/assets/training.css
Labels: internal

#914 docs: Update for finding types
  site/guide/_sidebar.yaml
  site/guide/model-validation/_add-finding-via-overview.qmd
  site/guide/model-validation/_add-finding-via-section.qmd
  site/guide/model-validation/_link-findings-to-reports.qmd
  site/guide/model-validation/_view-all-findings.qmd
  site/guide/model-validation/add-manage-model-findings.qmd
  site/guide/model-validation/add-section-finding.gif
  site/guide/model-validation/all-model-findings.png
  site/guide/model-validation/manage-finding-statuses.qmd
  site/guide/model-validation/manage-finding-types.qmd
  site/guide/model-validation/manage-model-finding-fields.qmd
  site/guide/model-validation/managing-model-validation.qmd
  site/guide/model-validation/model-specific-findings.png
  site/guide/model-validation/view-filter-model-findings.qmd
  site/training/validator-fundamentals/developing-challenger-models.qmd
  site/training/validator-fundamentals/finalizing-validation-reports.qmd
Labels: internal

#916 docs: Quick update for workflows User Action v2
  site/guide/model-workflows/_workflow-step-types.qmd
  site/guide/model-workflows/configure_user-action.png
Labels: internal

#913 infra: Separating notebook runs from docs deploy workflows
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
  .github/workflows/execute-pr-preview.yaml
  .github/workflows/execute-prod.yaml
  .github/workflows/execute-staging.yaml
  .github/workflows/validate-docs-site.yaml
Labels: internal

#915 Document checker updates for the EU AI Act
  site/guide/model-documentation/check-documentation-for-compliance.qmd
  site/guide/model-documentation/check-documents-for-compliance-gap-identified.png
  site/guide/model-documentation/check-documents-for-compliance-no-significant-gaps.png
  site/guide/model-documentation/check-documents-for-compliance-partial-gap.png
  site/guide/model-documentation/check-documents-for-compliance-review.png
  site/guide/model-documentation/check-documents-for-compliance-select-regulation.png
Labels: internal

#922 [TESTING] Merging a PR into `main-test`
  README.md
Labels: internal
