Repository validmind/documentation, pull requests merged in 2025-07, with the labels that each got.

#798 chore: update bucket, distro for prod docs deploy
  .github/workflows/deploy-docs-prod.yaml
Labels: internal

#822 chore: upgrade libxml2
  Dockerfile
  site/Dockerfile
Labels: internal

#813 docs: Workflows Broadcast step
  .github/workflows/validate-docs-site.yaml
  site/guide/model-workflows/_conditional-requirements.qmd
  site/guide/model-workflows/_workflow-step-types.qmd
  site/guide/model-workflows/configure_broadcast.png
  site/guide/model-workflows/example_broadcast-notif.png
  site/guide/model-workflows/example_broadcast.png
  site/guide/model-workflows/example_model-deployment-workflow.png
  site/guide/model-workflows/workflow-configuration-examples.qmd
Labels: internal

#830 docs: Manage model finding fields
  site/guide/_sidebar.yaml
  site/guide/model-inventory/_add-edit-inventory-fields.qmd
  site/guide/model-inventory/manage-model-inventory-fields.qmd
  site/guide/model-validation/manage-model-finding-fields.qmd
  site/guide/model-validation/managing-model-validation.qmd
Labels: internal

#796 Create new variable for Product name
  site/_variables.yml
Labels: internal

#819 Remove height constraint from navbar-brand
  site/styles.css
Labels: internal

#764 New home page integration
  .github/workflows/release_notes_check.yaml
  site/_quarto.yml
  site/assets/home-page/Ellipse 1 2.svg
  site/assets/home-page/Ellipse 1.svg
  site/assets/home-page/ValidMind MASTER Brand Assets_Logo-White R 2.svg
  site/assets/home-page/ValidMind MASTER Brand Assets_Logo-White R 3.svg
  site/assets/home-page/freckles_bckgd 2.svg
  site/assets/home-page/freckles_bckgd.svg
  site/assets/home-page/model_icon 2.svg
  site/assets/home-page/model_icon.svg
  site/assets/home-page/model_valid_icon 2.svg
  site/assets/home-page/model_valid_icon.svg
  site/assets/home-page/release_icon 2.svg
  site/assets/home-page/release_icon.svg
  site/assets/home-page/setup_icon 2.svg
  site/assets/home-page/setup_icon.svg
  site/developer/developer.css
  site/guide/configuration/managing-your-organization.qmd
  site/guide/guides.qmd
  site/index.qmd
  site/releases/_sidebar.yaml
  site/releases/highlights.qmd
  site/styles.css
  site/training/fake-tour/product-tour.qmd
Labels: documentation, internal

#842 Remove unused footnote
  site/about/overview-llm-features.qmd
Labels: bug, internal

#847 Cherry pick into `prod`
  internal/templates/videos/index.qmd
  site/_variables.yml
  site/developer/developer.css
  site/styles.css
  site/training/administrator-fundamentals/customizing-your-model-inventory.qmd
  site/training/administrator-fundamentals/onboarding-your-organization.qmd
  site/training/administrator-fundamentals/organizational-oversight-reporting.qmd
  site/training/administrator-fundamentals/using-validmind-for-model-risk-management.qmd
  site/training/developer-fundamentals/finalizing-model-documentation.qmd
  site/training/developer-fundamentals/implementing-custom-tests.qmd
  site/training/developer-fundamentals/learning-to-run-tests.qmd
  site/training/developer-fundamentals/using-validmind-for-model-development.qmd
  site/training/risk-governance-fundamentals.qmd/risk-governance-fundamentals.qmd
  site/training/training-templates/course-slides.qmd
  site/training/training.qmd
  site/training/validator-fundamentals/developing-challenger-models.qmd
  site/training/validator-fundamentals/finalizing-validation-reports.qmd
  site/training/validator-fundamentals/running-data-quality-tests.qmd
  site/training/validator-fundamentals/using-validmind-for-model-validation.qmd
Labels: internal

#849 Re-add make generate-sitemap action
  .github/workflows/lighthouse-check.yaml
  .github/workflows/validate-docs-site.yaml
Labels: bug

#851 Fix duplicated workflow contents
  .github/workflows/release_notes_check.yaml
Labels: bug, internal

#857 Update example and add alert email screenshot
  site/guide/monitoring/automated-alert-notification-email.png
  site/guide/monitoring/set-thresholds-and-alerts.qmd
Labels: documentation, internal

#860 docs: Manage platform notifications MVP
  site/_quarto.yml
  site/_variables.yml
  site/about/glossary/_validmind.qmd
  site/developer/validmind-library.qmd
  site/faq/_faq-activity.qmd
  site/faq/faq-documentation.qmd
  site/faq/faq-organizations.qmd
  site/faq/faq-reporting.qmd
  site/faq/faq-testing.qmd
  site/faq/faq-validation.qmd
  site/faq/faq-workflows.qmd
  site/get-started/common-steps/_before-you-begin.qmd
  site/get-started/get-started.qmd
  site/guide/_sidebar.yaml
  site/guide/access/_validmind-public-internet.qmd
  site/guide/access/accessing-validmind.qmd
  site/guide/access/email-verified.png
  site/guide/access/log-in-to-validmind.qmd
  site/guide/access/main-dashboard.png
  site/guide/access/organization-accept-invitation.png
  site/guide/access/organization-invitation-email.png
  site/guide/access/register-with-validmind.qmd
  site/guide/access/sample-models.png
  site/guide/access/signup-welcome-screen.png
  site/guide/access/verify-email.png
  site/guide/configuration/manage-platform-notifications.qmd
  site/guide/guides.qmd
  site/releases/2024/2024-dec-06/release-notes.qmd
  site/releases/2024/2024-dec-24/release-notes.qmd
  site/releases/2024/2024-mar-27/highlights.qmd
  site/releases/2024/2024-oct-22/release-notes.qmd
  site/releases/_how-to-upgrade.qmd
  site/support/_submit-feedback.qmd
  site/training/_training-register.qmd
Labels: internal

#869 hotfix: Applied product variables to homepage
  site/index.qmd
Labels: internal

#855 Add ValidMind Public REST API to docs site
  site/Makefile
  site/developer/_sidebar.yaml
  site/reference/validmind-rest-api-vm.qmd
  site/reference/vm-api.qmd
Labels: documentation, highlight
