Repository validmind/documentation, pull requests merged in 2025-05, with the labels that each got.

#707 Docs: Updated content block features
  site/_quarto.yml
  site/about/overview-model-documentation.qmd
  site/about/overview-model-risk-management.qmd
  site/faq/faq-documentation.qmd
  site/get-started/platform/explore-sample-model-documentation.qmd
  site/get-started/platform/register-your-first-model.qmd
  site/guide/guides.qmd
  site/guide/model-documentation/_add-content-block.qmd
  site/guide/model-documentation/add-content-block.gif
  site/guide/model-documentation/content_blocks/_generate-with-ai.qmd
  site/guide/model-documentation/content_blocks/_metric-over-time-block.qmd
  site/guide/model-documentation/content_blocks/_simple-text-block.qmd
  site/guide/model-documentation/content_blocks/_test-driven-block.qmd
  site/guide/model-documentation/generate-with-ai.gif
  site/guide/model-documentation/remove-test-driven-block.gif
  site/guide/model-documentation/remove-text-block.gif
  site/guide/model-documentation/test-driven-block-menu.png
  site/guide/model-documentation/work-with-content-blocks.qmd
  site/guide/model-documentation/work-with-test-results.qmd
  site/guide/model-inventory/register-models-in-inventory.qmd
  site/guide/model-validation/manage-validation-guidelines.qmd
  site/guide/monitoring/metrics-over-time-menu.png
  site/guide/monitoring/work-with-metrics-over-time.qmd
  site/guide/templates/_customize-documentation-templates-simplified.qmd
  site/guide/templates/customize-documentation-templates.qmd
  site/guide/templates/duplicate-template.gif
  site/guide/templates/edit-template-outline.gif
  site/guide/templates/edit-yaml-template.gif
  site/guide/templates/manage-text-block-library.qmd
  site/guide/templates/swap-documentation-templates.qmd
  site/guide/templates/view-documentation-templates.qmd
  site/guide/templates/working-with-documentation-templates.qmd
  site/releases/2023/release-notes-2023-jul-24.qmd
  site/releases/2023/release-notes-2023-jun-22.qmd
  site/releases/2024/2024-dec-06/release-notes.qmd
  site/releases/2024/2024-feb-14/highlights.qmd
  site/releases/2024/2024-jan-18/highlights.qmd
  site/releases/2024/2024-may-22/release-notes.qmd
  site/training/_training-register.qmd
  site/training/administrator-fundamentals/administrator-fundamentals.qmd
  site/training/developer-fundamentals/finalizing-model-documentation.qmd
  site/training/developer-fundamentals/implementing-custom-tests.qmd
  site/training/developer-fundamentals/learning-to-run-tests.qmd
  site/training/developer-fundamentals/using-validmind-for-model-development.qmd
Labels: documentation

#714 hotfix: -`include-after-body` in execution profiles
  site/_quarto-exe-demo.yml
  site/_quarto-exe-prod.yml
  site/_quarto-exe-staging.yml
Labels: internal

#717 feat: repair helm chart conflicts
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
  site/Makefile
Labels: internal

#719 Merge `staging` into `prod`
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
  site/Makefile
Labels: internal

#722 Edited the FAQ testing file (faq-testing.qmd). Added 2 new sections.
  site/faq/faq-testing.qmd
Labels: internal

#710 Enable cloning specific installation repo branches in `Makefile`
  site/Makefile
Labels: infrastructure, internal

#727 infra: Remove conditional execution for staging and prod
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
Labels: internal

#729 `prod` hotfix — Notebook execution filters
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
Labels: internal
