Repository validmind/documentation, pull requests merged in 2025-06, with the labels that each got.

#740 training: Implemented new slideover overlays for developer & validator fundamentals
  site/_extensions/nrichers/slideover/_extension.yml
  site/_extensions/nrichers/slideover/custom-slideover.css
  site/_extensions/nrichers/slideover/slideover.css
  site/_extensions/nrichers/slideover/slideover.js
  site/guide/model-validation/_add-model-findings.qmd
  site/guide/model-validation/_track_issue_resolution.qmd
  site/guide/model-workflows/_model-workflows-see.qmd
  site/guide/model-workflows/_model-workflows-transition.qmd
  site/training/assets/validmind-slideover.css
  site/training/developer-fundamentals/finalizing-model-documentation.qmd
  site/training/developer-fundamentals/implementing-custom-tests.qmd
  site/training/developer-fundamentals/learning-to-run-tests.qmd
  site/training/developer-fundamentals/using-validmind-for-model-development.qmd
  site/training/training-templates/course-slides.qmd
  site/training/validator-fundamentals/developing-challenger-models.qmd
  site/training/validator-fundamentals/finalizing-validation-reports.qmd
  site/training/validator-fundamentals/running-data-quality-tests.qmd
  site/training/validator-fundamentals/using-validmind-for-model-validation.qmd
  site/training/validator-fundamentals/validator-fundamentals.qmd
Labels: internal

#745 placeholders: Updated "Get Started" landing
  site/_quarto.yml
  site/about/overview.qmd
  site/about/validmind-lifecycle.jpg
  site/get-started/_sidebar.yaml
  site/get-started/administrator/quickstart-administrator.qmd
  site/get-started/developer/google-colab.png
  site/get-started/developer/quickstart-developer.qmd
  site/get-started/developer/try-with-colab.qmd
  site/get-started/get-started.qmd
  site/get-started/quickstart.qmd
  site/get-started/validator/quickstart-validator.qmd
Labels: internal

#747 Fix links in training faq
  site/training/program/training-faq.qmd
Labels: bug

#751 feat: make docs repo safe for omnibus
  .github/workflows/deploy-docs-prod.yaml
Labels: internal

#765 docs: Workflows history update
  site/about/contributing/style-guide/conventions.qmd
  site/guide/model-documentation/submit-for-approval.qmd
  site/guide/model-workflows/_review-active-workflows.qmd
  site/guide/model-workflows/manage-model-stages.qmd
  site/guide/model-workflows/manage-model-workflows.qmd
  site/guide/model-workflows/setting-up-model-workflows.qmd
  site/guide/model-workflows/transition-model-workflows.qmd
  site/releases/2024/2024-jul-22/release-notes.qmd
  site/releases/2024/2024-may-22/release-notes.qmd
  site/training/developer-fundamentals/finalizing-model-documentation.qmd
  site/training/validator-fundamentals/finalizing-validation-reports.qmd
Labels: internal

#778 hotfix: Updated workflows to pull dependencies directly from `validmind-library`
  .github/actions/demo-notebook/action.yml
  .github/actions/prod-notebook/action.yml
  .github/actions/staging-notebook/action.yml
  .github/workflows/validate-docs-site.yaml
Labels: internal

#782 Create rebrandable docs site with K8s manifest configuration
  .gitignore
  Dockerfile
  README.md
  kind-config.yaml
  site/Makefile
  site/_quarto-docker.yml
  site/_quarto.yml
  site/_variables.yml
  site/favicon.svg
  site/index.qmd
  site/logo.svg
  site/releases/2025/2025-apr-24/release-notes.qmd
  site/scripts/docker_entrypoint.sh
  site/scripts/make_configurable.sh
  site/scripts/modify_urls.sh
  site/validmind-docs.yaml
  site/validmind.png
  validmind-docs-deployment.yaml
  validmind-docs.yaml
Labels: infrastructure, highlight

#784 Hotfix for Kind environment variable override
  Dockerfile
  site/scripts/docker_entrypoint.sh
Labels: bug, internal

#789 Highlight rebranding instructions and add example
  README.md
  site/custom-validmind-docs.yaml
Labels: internal
