Repository validmind/documentation, pull requests merged in 2025-04, with the labels that each got.

#686 Documentation: Manage model stakeholder types
  site/_quarto.yml
  site/guide/configuration/_manage-roles.qmd
  site/guide/configuration/manage-model-stakeholder-types.qmd
  site/guide/configuration/managing-users.qmd
  site/guide/model-inventory/edit-model-inventory-fields.qmd
  site/guide/model-inventory/manage-model-inventory-fields.qmd
Labels: internal

#687 User guide updates for attestation
  site/_quarto.yml
  site/about/fine-print/data-privacy-policy.qmd
  site/about/glossary/_attestation.qmd
  site/about/glossary/glossary.qmd
  site/guide/attestation/attestation-banner.png
  site/guide/attestation/complete-attestation-questionnaires.qmd
  site/guide/attestation/edit-questionnaire-template.gif
  site/guide/attestation/review-attestation-questionnaires.qmd
  site/guide/attestation/review-attestation.png
  site/guide/attestation/set-up-attestations.qmd
  site/guide/attestation/sign-off-attestation.png
  site/guide/attestation/start-attestation.png
  site/guide/attestation/working-with-attestations.qmd
  site/guide/guides.qmd
  site/theme.scss
Labels: documentation, highlight

#695 Release Notes — Unified version `23.03.05`
  internal/templates/yearly-releases.qmd
  release-scripts/generate-release-notes.ipynb
  release-scripts/generate_release_objects.py
  release-scripts/year-end-cleanup.ipynb
  release-scripts/yearly_cleanup.py
  site/Makefile
  site/_quarto.yml
  site/developer/samples-jupyter-notebooks.qmd
  site/faq/faq-collaboration.qmd
  site/faq/faq-documentation.qmd
  site/faq/faq-integrations.qmd
  site/faq/faq-inventory.qmd
  site/faq/faq-organizations.qmd
  site/faq/faq-privacy.qmd
  site/faq/faq-reporting.qmd
  site/faq/faq-testing.qmd
  site/faq/faq-validation.qmd
  site/faq/faq-workflows.qmd
  site/faq/faq.qmd
  site/guide/configuration/_manage-roles.qmd
  site/index.qmd
  site/releases/2023/2023-aug-15/highlights.qmd
  site/releases/2023/2023-dec-13/highlights.qmd
  site/releases/2023/2023-nov-09/highlights.qmd
  site/releases/2023/2023-oct-25/highlights.qmd
  site/releases/2023/2023-releases.qmd
  site/releases/2023/2023-sep-27/highlights.qmd
  site/releases/2023/release-notes-2023-jul-24.qmd
  site/releases/2023/release-notes-2023-jun-22.qmd
  site/releases/2023/release-notes-2023-may-30.qmd
  site/releases/2024/2024-aug-13/release-notes.qmd
  site/releases/2024/2024-dec-06/release-notes.qmd
  site/releases/2024/2024-dec-24/release-notes.qmd
  site/releases/2024/2024-feb-14/highlights.qmd
  site/releases/2024/2024-jan-18/highlights.qmd
  site/releases/2024/2024-jan-26/highlights.qmd
  site/releases/2024/2024-jul-22/release-notes.qmd
  site/releases/2024/2024-jun-10/release-notes.qmd
  site/releases/2024/2024-mar-27/highlights.qmd
  site/releases/2024/2024-may-22/release-notes.qmd
  site/releases/2024/2024-oct-22/release-notes.qmd
  site/releases/2024/2024-releases.qmd
  site/releases/2024/2024-sep-09/release-notes.qmd
  site/releases/2024/2024-sep-25/release-notes.qmd
  site/releases/2025/2025-apr-24/release-notes.qmd
  site/releases/2025/2025-jan-31/release-notes.qmd
  site/releases/2025/2025-mar-07/release-notes.qmd
  site/releases/_sidebar.yaml
  site/releases/all-releases.qmd
  site/releases/breaking-changes/breaking-changes.qmd
  site/validmind/_sidebar.yml
  site/validmind/validmind.qmd
  site/validmind/validmind/version.qmd
Labels: internal

#699 Fix merge conflicts for prod push #698
  internal/templates/yearly-releases.qmd
  release-scripts/generate-release-notes.ipynb
  release-scripts/generate_release_objects.py
  release-scripts/year-end-cleanup.ipynb
  release-scripts/yearly_cleanup.py
  site/Makefile
  site/_quarto.yml
  site/developer/samples-jupyter-notebooks.qmd
  site/faq/faq-collaboration.qmd
  site/faq/faq-documentation.qmd
  site/faq/faq-integrations.qmd
  site/faq/faq-inventory.qmd
  site/faq/faq-organizations.qmd
  site/faq/faq-privacy.qmd
  site/faq/faq-reporting.qmd
  site/faq/faq-testing.qmd
  site/faq/faq-validation.qmd
  site/faq/faq-workflows.qmd
  site/faq/faq.qmd
  site/guide/configuration/_manage-roles.qmd
  site/index.qmd
  site/releases/2023/2023-aug-15/highlights.qmd
  site/releases/2023/2023-dec-13/highlights.qmd
  site/releases/2023/2023-nov-09/highlights.qmd
  site/releases/2023/2023-oct-25/highlights.qmd
  site/releases/2023/2023-releases.qmd
  site/releases/2023/2023-sep-27/highlights.qmd
  site/releases/2023/release-notes-2023-jul-24.qmd
  site/releases/2023/release-notes-2023-jun-22.qmd
  site/releases/2023/release-notes-2023-may-30.qmd
  site/releases/2024/2024-aug-13/release-notes.qmd
  site/releases/2024/2024-dec-06/release-notes.qmd
  site/releases/2024/2024-dec-24/release-notes.qmd
  site/releases/2024/2024-feb-14/highlights.qmd
  site/releases/2024/2024-jan-18/highlights.qmd
  site/releases/2024/2024-jan-26/highlights.qmd
  site/releases/2024/2024-jul-22/release-notes.qmd
  site/releases/2024/2024-jun-10/release-notes.qmd
  site/releases/2024/2024-mar-27/highlights.qmd
  site/releases/2024/2024-may-22/release-notes.qmd
  site/releases/2024/2024-oct-22/release-notes.qmd
  site/releases/2024/2024-releases.qmd
  site/releases/2024/2024-sep-09/release-notes.qmd
  site/releases/2024/2024-sep-25/release-notes.qmd
  site/releases/2025/2025-apr-24/release-notes.qmd
  site/releases/2025/2025-jan-31/release-notes.qmd
  site/releases/2025/2025-mar-07/release-notes.qmd
  site/releases/_sidebar.yaml
  site/releases/all-releases.qmd
  site/releases/breaking-changes/breaking-changes.qmd
  site/validmind/_sidebar.yml
  site/validmind/validmind.qmd
  site/validmind/validmind/version.qmd
Labels: internal

#696 Automatically set the year in footer & fix links to main site
  site/_extensions/gadenbuie/now/_extension.yml
  site/_extensions/gadenbuie/now/now.lua
  site/_quarto.yml
  site/about/fine-print/data-privacy-policy.qmd
  site/about/fine-print/license-agreement.qmd
  site/about/overview-llm-features.qmd
Labels: infrastructure, internal

#693 fix: [sc-9632] Add missing "Export ongoing monitoring document" section to docs
  site/_quarto.yml
  site/about/overview-model-risk-management.qmd
  site/faq/faq-documentation.qmd
  site/faq/faq-reporting.qmd
  site/guide/guides.qmd
  site/guide/model-validation/working-with-model-findings.qmd
  site/guide/reporting/export-documentation.qmd
  site/releases/2023/release-notes-2023-may-30.qmd
  site/releases/2025/2025-mar-07/release-notes.qmd
Labels: documentation, internal

#702 Merge `staging` into `prod`
  site/_extensions/gadenbuie/now/_extension.yml
  site/_extensions/gadenbuie/now/now.lua
  site/_quarto.yml
  site/about/fine-print/data-privacy-policy.qmd
  site/about/fine-print/license-agreement.qmd
  site/about/overview-llm-features.qmd
  site/about/overview-model-risk-management.qmd
  site/faq/faq-documentation.qmd
  site/faq/faq-reporting.qmd
  site/guide/guides.qmd
  site/guide/model-validation/working-with-model-findings.qmd
  site/guide/reporting/export-documentation.qmd
  site/releases/2023/release-notes-2023-may-30.qmd
  site/releases/2025/2025-mar-07/release-notes.qmd
Labels: internal

#703 fix: remove helm repo path from s3 sync commands
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/deploy-docs-staging.yaml
  site/Makefile
Labels: internal
