Repository validmind/documentation, pull requests merged in 2025-03, with the labels that each got.

#666 Release notes to sprint 68 — 25.02
  site/_quarto.yml
  site/index.qmd
  site/releases/2025/2025-mar-07/export-validation-report.png
  site/releases/2025/2025-mar-07/release-notes.qmd
Labels: internal

#672 feat: example implementation of trigger in other repo
  .github/workflows/test_installation_trigger.yaml
Labels: infrastructure, internal

#678 Remove defunct deploy-demo make action
  site/Makefile
Labels: infrastructure, internal

#674 Add URL configuration to Docker images
  .gitignore
  Dockerfile
  README.md
  site/Dockerfile
  site/Makefile
  site/_quarto-docker.yml
  site/_variables.yml
  site/developer/samples-jupyter-notebooks.qmd
  site/get-started/developer/try-with-jupyterhub.qmd
  site/releases/2024/2024-may-22/release-notes.qmd
  site/releases/2024/2024-oct-22/release-notes.qmd
  site/scripts/docker_entrypoint.sh
  site/scripts/modify_urls.sh
  site/training/_training-register.qmd
  site/training/developer-fundamentals/developer-fundamentals.qmd
  site/training/program/learning-paths.qmd
  validmind-docs.yaml
Labels: infrastructure

#677 feat: extend build to include private section
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/validate-docs-site.yaml
  .gitignore
  site/Makefile
  site/_quarto.yml
Labels: infrastructure, internal

#680 Fix merge conflict for `staging`
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/validate-docs-site.yaml
  .gitignore
  Dockerfile
  README.md
  site/Dockerfile
  site/Makefile
  site/_quarto-docker.yml
  site/_quarto.yml
  site/_variables.yml
  site/developer/samples-jupyter-notebooks.qmd
  site/get-started/developer/try-with-jupyterhub.qmd
  site/releases/2024/2024-may-22/release-notes.qmd
  site/releases/2024/2024-oct-22/release-notes.qmd
  site/scripts/docker_entrypoint.sh
  site/scripts/modify_urls.sh
  site/training/_training-register.qmd
  site/training/developer-fundamentals/developer-fundamentals.qmd
  site/training/program/learning-paths.qmd
  validmind-docs.yaml
Labels: internal

#682 Cherry pick #677 into `prod`
  .github/workflows/deploy-docs-prod.yaml
  .github/workflows/validate-docs-site.yaml
  .gitignore
  site/_quarto.yml
  test_results.md
Labels: internal

#676 Enable cloning at a specific release tag
  site/Makefile
Labels: infrastructure, internal
